### ISSUE TITLE
Getty endpoint does not provide results

### ISSUE THREAD

**Issue by workergnome** [reconciliation-api/testbench#12]
using the URL https://services.getty.edu/vocab/reconcile/ and they type `/ulan`, a query for "Robert" generates the following error:

```
Error: undefined is not an object (evaluating 't.q0.result')
```

See attached screenshot for configuration.

<img width="1428" alt="Screen Shot 2020-01-08 at 1 49 49 PM" src="https://user-images.githubusercontent.com/34536/72019059-c643e480-321d-11ea-8b5b-3e7c799cae28.png">

**Comment by wetneb** [comment]
That seems to be due to the fact that the endpoint does not correctly implement JSONP for reconciliation queries: as soon as a `callback` parameter is supplied, the service manifest is returned, ignoring the queries supplied.
See https://services.getty.edu/vocab/reconcile/?queries={%22q0%22%3A{%22query%22%3A%22test%22}}&callback=mycallback which returns the manifest while it should return reconciliation candidates for the query.

That being said the testbench should display a cleaner error message in that case.

**Comment by wetneb** [comment]
It seems to work well now.
