### ISSUE TITLE
Test bench for lobid-organisations returns error

### ISSUE THREAD

**Issue by shigapov** [reconciliation-api/testbench#23]
Test bench for the endpoint https://lobid.org/organisations/reconcile with the query 'basf' returns:
''Error: Cannot read property 'result' of undefined" in Opera,
"Error: t.q0 is undefined" in Firefox,
"Error: undefined is not an object (evaluating 't.q0.result')" in Safari.

**Comment by wetneb** [comment]
That seems to be because the endpoint does not support reconciliation queries submitted by GET:
https://lobid.org/organisations/reconcile?queries=%7B%22q0%22%3A%7B%22query%22%3A%22basf%22%7D%7D

The testbench should try both GET and POST, I would say. When an unexpected reply is received we should show a validation error from the JSON schema instead of our own Javascript exception.

**Comment by wetneb** [comment]
Closed by #69.
